backend:
  name: github
  repo: thepodz/ajaxphotomap
  branch: main
  app_id: Ov23liIFvs6eHSwtluRx

media_folder: "photos"
public_folder: "photos"

collections:
  - name: "photos_data"
    label: "Ajax Photo Collection"
    files:
      - name: "photos_list"
        label: "Photos List"
        file: "photos.json"
        format: "json"
        fields:
          - label: "Photos"
            name: "photos"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Caption", name: "caption", widget: "text" }
              - { label: "Image", name: "imageUrl", widget: "image" }
              - { label: "Longitude", name: "lng", widget: "number", value_type: "float" }
              - { label: "Latitude", name: "lat", widget: "number", value_type: "float" }
